#!/bin/sh
# File generated by ocamlbuild

cd /mnt/nfs/netapp2/students/cbierman/Desktop/PLC/HW4

rm -f copyingGC.annot
# Also clean the script itself
rm -f /mnt/nfs/netapp2/students/cbierman/Desktop/PLC/HW4/_build/sanitize.sh
